### ISSUE TITLE
Miscellaneous fixes

### ISSUE THREAD

**Issue by alexgavrisco** [AlexandrYaltychenko/PAD_Lab1#1]
@AlexandrYaltychenko 
- [x] Add IDE-related files to .gitignore
- [x] Describe the broker's protocol (as described in conditions)
- [x] How to run/build the project (add some instructions)?

**Comment by AlexandrYaltychenko** [comment]
@Alexx-G 
Thank you for your review!
I ignored IDE-related files, added the description of the broker's protocol and some instructions how to run/build the project.
